allowBuilds:
  msgpackr-extract: false
minimumReleaseAgeExclude:
  - '@opencode/ai@2.0.24'
  - '@opencode/client@2.0.24'
  - '@opencode/plugin@2.0.24'
  - '@opencode/protocol@2.0.24'
  - '@opencode/schema@2.0.24'
  - '@opencode/util@2.0.24'
